version: '3.8'
services:
  function:
    container_name: ${appName_PROJECT}
    build:
      context: ./
      dockerfile: ./Dockerfile
    env_file:
      - .env
      - ${appName_DIR}/.env
    ports:
      - '${PORT}:${PORT}'
