version: '3.8'
services:
  function:
    build:
      context: ${appName_DIR}
      dockerfile: ${appName_TMP_PATH}/Dockerfile
    env_file:
      - ./.env
    container_name: ${appName_PROJECT}
    volumes:
      - ${appName_DIR}:/usr/src/app
      - /usr/src/app/.config
    ports:
      - ${PORT}:${PORT}
