version: '3.8'
services:
  function:
    build:
      context: ${appName_DIR}
      dockerfile: ./Dockerfile
    env_file:
      - ./.env
    container_name: ${appName_PROJECT}
    ports:
      - ${PORT}:${PORT}
